// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: card_history.sql

package db

import (
	"context"
)

const decrementFlashcardScore = `-- name: DecrementFlashcardScore :exec
UPDATE card_history SET score = score - 1, times_attempted = times_attempted + 1 WHERE user_id = $1 AND card_id = $2
`

type DecrementFlashcardScoreParams struct {
	UserID int32
	CardID int32
}

func (q *Queries) DecrementFlashcardScore(ctx context.Context, arg DecrementFlashcardScoreParams) error {
	_, err := q.db.Exec(ctx, decrementFlashcardScore, arg.UserID, arg.CardID)
	return err
}

const incrementFlashcardScore = `-- name: IncrementFlashcardScore :exec
UPDATE card_history SET score = score + 1, times_attempted = times_attempted + 1 WHERE user_id = $1 AND card_id = $2
`

type IncrementFlashcardScoreParams struct {
	UserID int32
	CardID int32
}

func (q *Queries) IncrementFlashcardScore(ctx context.Context, arg IncrementFlashcardScoreParams) error {
	_, err := q.db.Exec(ctx, incrementFlashcardScore, arg.UserID, arg.CardID)
	return err
}
