// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: class_user.sql

package db

import (
	"context"
)

const getClasses = `-- name: GetClasses :many
SELECT class_id, role, name FROM class_user JOIN classes ON class_user.class_id = classes.id
WHERE user_id = $1
`

type GetClassesRow struct {
	ClassID int32
	Role    string
	Name    string
}

func (q *Queries) GetClasses(ctx context.Context, userID int32) ([]GetClassesRow, error) {
	rows, err := q.db.Query(ctx, getClasses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetClassesRow
	for rows.Next() {
		var i GetClassesRow
		if err := rows.Scan(&i.ClassID, &i.Role, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembers = `-- name: GetMembers :many
SELECT user_id, class_id, role, first_name, last_name
FROM class_user JOIN users ON class_user.user_id = users.id
WHERE class_id = $1
`

type GetMembersRow struct {
	UserID    int32
	ClassID   int32
	Role      string
	FirstName string
	LastName  string
}

func (q *Queries) GetMembers(ctx context.Context, classID int32) ([]GetMembersRow, error) {
	rows, err := q.db.Query(ctx, getMembers, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersRow
	for rows.Next() {
		var i GetMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.ClassID,
			&i.Role,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudents = `-- name: GetStudents :many
SELECT user_id, class_id, role, first_name, last_name
FROM class_user JOIN users ON class_user.user_id = users.id
WHERE class_id = $1 AND role = 'Student'
`

type GetStudentsRow struct {
	UserID    int32
	ClassID   int32
	Role      string
	FirstName string
	LastName  string
}

func (q *Queries) GetStudents(ctx context.Context, classID int32) ([]GetStudentsRow, error) {
	rows, err := q.db.Query(ctx, getStudents, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentsRow
	for rows.Next() {
		var i GetStudentsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ClassID,
			&i.Role,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinClass = `-- name: JoinClass :exec
INSERT INTO class_user (user_id, class_id, role) VALUES ($1, $2, $3)
`

type JoinClassParams struct {
	UserID  int32
	ClassID int32
	Role    string
}

func (q *Queries) JoinClass(ctx context.Context, arg JoinClassParams) error {
	_, err := q.db.Exec(ctx, joinClass, arg.UserID, arg.ClassID, arg.Role)
	return err
}

const leaveClass = `-- name: LeaveClass :exec
DELETE FROM class_user WHERE user_id = $1
`

func (q *Queries) LeaveClass(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, leaveClass, userID)
	return err
}
