// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: class_set.sql

package db

import (
	"context"
)

const addSet = `-- name: AddSet :exec
INSERT INTO class_set (class_id,set_id) VALUES ($1, $2)
`

type AddSetParams struct {
	ClassID int32
	SetID   int32
}

func (q *Queries) AddSet(ctx context.Context, arg AddSetParams) error {
	_, err := q.db.Exec(ctx, addSet, arg.ClassID, arg.SetID)
	return err
}

const removeSet = `-- name: RemoveSet :exec
DELETE FROM class_set WHERE class_id = $1 AND set_id = $2
`

type RemoveSetParams struct {
	ClassID int32
	SetID   int32
}

func (q *Queries) RemoveSet(ctx context.Context, arg RemoveSetParams) error {
	_, err := q.db.Exec(ctx, removeSet, arg.ClassID, arg.SetID)
	return err
}
