// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: classes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClass = `-- name: CreateClass :execresult
INSERT INTO classes (name, description, join_code, teacher_id) VALUES ($1, $2, $3, $4)
`

type CreateClassParams struct {
	Name        string
	Description string
	JoinCode    string
	TeacherID   pgtype.Int4
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, createClass,
		arg.Name,
		arg.Description,
		arg.JoinCode,
		arg.TeacherID,
	)
}

const deleteClass = `-- name: DeleteClass :execresult
DELETE FROM classes WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteClass, id)
}

const getClassById = `-- name: GetClassById :one
SELECT id, name, description, join_code, teacher_id, created_at, updated_at FROM classes WHERE id = $1
`

func (q *Queries) GetClassById(ctx context.Context, id int32) (Class, error) {
	row := q.db.QueryRow(ctx, getClassById, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClasses = `-- name: ListClasses :many
SELECT id, name, description, join_code, teacher_id, created_at, updated_at FROM classes ORDER BY name
`

func (q *Queries) ListClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.JoinCode,
			&i.TeacherID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :execresult
UPDATE classes SET name = $1, description = $2, join_code = $3, teacher_id = $4, updated_at = NOW() WHERE id = $5
`

type UpdateClassParams struct {
	Name        string
	Description string
	JoinCode    string
	TeacherID   pgtype.Int4
	ID          int32
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, updateClass,
		arg.Name,
		arg.Description,
		arg.JoinCode,
		arg.TeacherID,
		arg.ID,
	)
}
