// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CardHistory struct {
	UserID         int32
	CardID         int32
	Score          int32
	TimesAttempted int32
	IsMastered     bool
	CreatedAt      pgtype.Timestamp
}

type Class struct {
	ID               int32
	ClassName        string
	ClassDescription string
	JoinCode         pgtype.Text
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type ClassSet struct {
	ClassID int32
	SetID   int32
}

type ClassUser struct {
	UserID  int32
	ClassID int32
	Role    string
}

type Flashcard struct {
	ID        int32
	Front     string
	Back      string
	SetID     int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type FlashcardSet struct {
	ID             int32
	SetName        string
	SetDescription string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type SetUser struct {
	UserID    int32
	SetID     int32
	SetScore  pgtype.Int4
	IsPrivate bool
}

type User struct {
	ID        int32
	Username  string
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
