// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClass = `-- name: CreateClass :exec
INSERT INTO classes (name, description, join_code, teacher_id) VALUES ($1, $2, $3, $4)
`

type CreateClassParams struct {
	Name        string
	Description string
	JoinCode    string
	TeacherID   pgtype.Int4
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) error {
	_, err := q.db.Exec(ctx, createClass,
		arg.Name,
		arg.Description,
		arg.JoinCode,
		arg.TeacherID,
	)
	return err
}

const createFlashCard = `-- name: CreateFlashCard :exec
INSERT INTO flashcards (front, back, set_id) VALUES ($1, $2, $3)
`

type CreateFlashCardParams struct {
	Front string
	Back  string
	SetID int32
}

func (q *Queries) CreateFlashCard(ctx context.Context, arg CreateFlashCardParams) error {
	_, err := q.db.Exec(ctx, createFlashCard, arg.Front, arg.Back, arg.SetID)
	return err
}

const createFlashCardSet = `-- name: CreateFlashCardSet :exec
INSERT INTO flashcard_sets (id, name, description) VALUES ($1, $2, $3)
`

type CreateFlashCardSetParams struct {
	ID          int32
	Name        string
	Description string
}

func (q *Queries) CreateFlashCardSet(ctx context.Context, arg CreateFlashCardSetParams) error {
	_, err := q.db.Exec(ctx, createFlashCardSet, arg.ID, arg.Name, arg.Description)
	return err
}

const deleteFlashCard = `-- name: DeleteFlashCard :exec
DELETE FROM flashcards WHERE id = $1
`

func (q *Queries) DeleteFlashCard(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFlashCard, id)
	return err
}

const deleteFlashCardSet = `-- name: DeleteFlashCardSet :exec
DELETE FROM flashcard_sets WHERE id = $1
`

func (q *Queries) DeleteFlashCardSet(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteFlashCardSet, id)
	return err
}

const getClass = `-- name: GetClass :one
SELECT id, name, description, join_code, teacher_id, created_at, updated_at FROM classes WHERE id = $1
`

func (q *Queries) GetClass(ctx context.Context, id int32) (Class, error) {
	row := q.db.QueryRow(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.JoinCode,
		&i.TeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClasses = `-- name: GetClasses :many
SELECT id, name, description, join_code, teacher_id, created_at, updated_at FROM classes
`

func (q *Queries) GetClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, getClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.JoinCode,
			&i.TeacherID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlashCard = `-- name: GetFlashCard :one
SELECT id, front, back, set_id, created_at, updated_at FROM flashcards WHERE id = $1
`

func (q *Queries) GetFlashCard(ctx context.Context, id int32) (Flashcard, error) {
	row := q.db.QueryRow(ctx, getFlashCard, id)
	var i Flashcard
	err := row.Scan(
		&i.ID,
		&i.Front,
		&i.Back,
		&i.SetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFlashCardSet = `-- name: GetFlashCardSet :one
SELECT id, name, description, created_at, updated_at FROM flashcard_sets WHERE id = $1
`

func (q *Queries) GetFlashCardSet(ctx context.Context, id int32) (FlashcardSet, error) {
	row := q.db.QueryRow(ctx, getFlashCardSet, id)
	var i FlashcardSet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, first_name, last_name, email, password, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, first_name, last_name, email, password, created_at, updated_at FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :exec
UPDATE classes SET name = $1, description = $2, join_code = $3, teacher_id = $4 WHERE id = $5
`

type UpdateClassParams struct {
	Name        string
	Description string
	JoinCode    string
	TeacherID   pgtype.Int4
	ID          int32
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) error {
	_, err := q.db.Exec(ctx, updateClass,
		arg.Name,
		arg.Description,
		arg.JoinCode,
		arg.TeacherID,
		arg.ID,
	)
	return err
}

const updateFlashCard = `-- name: UpdateFlashCard :exec
UPDATE flashcards SET front = $1, back = $2 WHERE id = $3
`

type UpdateFlashCardParams struct {
	Front string
	Back  string
	ID    int32
}

func (q *Queries) UpdateFlashCard(ctx context.Context, arg UpdateFlashCardParams) error {
	_, err := q.db.Exec(ctx, updateFlashCard, arg.Front, arg.Back, arg.ID)
	return err
}

const updateFlashCardSet = `-- name: UpdateFlashCardSet :exec
UPDATE flashcard_sets SET name = $1, description = $2 WHERE id = $3
`

type UpdateFlashCardSetParams struct {
	Name        string
	Description string
	ID          int32
}

func (q *Queries) UpdateFlashCardSet(ctx context.Context, arg UpdateFlashCardSetParams) error {
	_, err := q.db.Exec(ctx, updateFlashCardSet, arg.Name, arg.Description, arg.ID)
	return err
}
